spring:
  kafka:
    bootstrap-servers: cuodn3l77u3vj96efgc0.any.eu-central-1.mpx.prd.cloud.redpanda.com:9092
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-256
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="andrew" password="9UtAuujuT1DJgh4cV5Qna7XNN0nfbI";
